---
# Handle plugins

- name: "{{ jenkins_delay_s }}s delay while starting Jenkins"
  wait_for: port=8080 delay={{ jenkins_delay_s }}
  tags: jenkins
  
- name: "Create Jenkins destination directory: {{ jenkins_dest }}"
  sudo: yes
  file: path={{ jenkins_dest }} state=directory
  tags: jenkins
  
- name: Get Jenkins CLI from localhost
  sudo: yes
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest={{ jenkins.cli_dest }} mode=0440
  tags: jenkins

- name: Get Jenkins updates
  sudo: yes
  get_url: url=http://updates.jenkins-ci.org/update-center.json dest={{ jenkins.updates_dest }} thirsty=yes mode=0440
  register: jenkins_updates
  tags: jenkins

- name: Update-center Jenkins
  sudo: yes
  action: "shell cat {{ jenkins.updates_dest }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed
  notify:
    - 'Safe restart Jenkins'
  tags: jenkins
